
package hospital_managment_system;
import hospital_managment_system.DatabaseHandler;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Financials extends javax.swing.JDialog {

    

    int id;
    double ch;
    double pa;
    double mo;
    
    /**
     * Creates new form Financials
     */
    public Financials(java.awt.Dialog parent, boolean modal, int Id, double cha, double p, double m) {
        super(parent, modal);
        initComponents();
        setTitle("Financials");
        id = Id;
        ch = DatabaseHandler.getPatientTotalChargeById(id);
        pa = DatabaseHandler.getPatientTotalDepositedById(id);
        mo = DatabaseHandler.getPatientMoneyToReturnById(id);
        TotalChargeTextField.setText(String.valueOf(ch));
        TotalPaidTextField.setText(String.valueOf(pa));
        MoneyLabel.setText(String.valueOf(pa-ch));
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TotalChargeTextField = new javax.swing.JTextField();
        TotalPaidTextField = new javax.swing.JTextField();
        SaveMoneyButton = new javax.swing.JButton();
        MoneyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Total Charge:");

        jLabel2.setText("Total Paid:");

        jLabel3.setText("Money To Return:");

        TotalChargeTextField.setText(String.valueOf(ch));

        TotalPaidTextField.setText(String.valueOf(pa));
        TotalPaidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPaidTextFieldActionPerformed(evt);
            }
        });

        SaveMoneyButton.setText("Save");
        SaveMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMoneyButtonActionPerformed(evt);
            }
        });

        MoneyLabel.setText(String.valueOf(mo));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalPaidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MoneyLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(SaveMoneyButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TotalChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TotalPaidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MoneyLabel))
                .addGap(42, 42, 42)
                .addComponent(SaveMoneyButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalPaidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPaidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPaidTextFieldActionPerformed

    private void SaveMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMoneyButtonActionPerformed
        // TODO add your handling code here:
        double charge = Double.valueOf(TotalChargeTextField.getText());
        double paid = Double.valueOf(TotalPaidTextField.getText());
        double moneyToReturn = paid - charge;
        
        try{
            Connection conn=DatabaseHandler.getConnection();
            
        if (conn == null) {
        JOptionPane.showMessageDialog(null, "Connection failed");
        } else {
        System.out.println("Connection successful!");
        }
        
        Statement stmt = conn.createStatement();
        String sql;
        sql ="UPDATE `hospitalmanagmentsystem` SET `TotalCharge`='"+charge+"',`TotalDeposited`='"+paid+"',`MoneyToReturn`='"+moneyToReturn+"' WHERE ID = "+id+"";
        stmt.executeUpdate(sql);

        
            JOptionPane.showMessageDialog(null, "Financals Saved Successfully");
        
        ch = DatabaseHandler.getPatientTotalChargeById(id);
        pa = DatabaseHandler.getPatientTotalDepositedById(id);
        mo = DatabaseHandler.getPatientMoneyToReturnById(id);
        TotalChargeTextField.setText(String.valueOf(ch));
        TotalPaidTextField.setText(String.valueOf(pa));
        MoneyLabel.setText(String.valueOf(mo));
            
            stmt.close();
            conn.close();
            

            
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error Occured Try Again");
        }
    }//GEN-LAST:event_SaveMoneyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MoneyLabel;
    private javax.swing.JButton MoneySaveButton;
    private javax.swing.JButton MoneySaveButton1;
    private javax.swing.JButton MoneySaveButton2;
    private javax.swing.JButton SaveMoneyButton;
    private javax.swing.JTextField TotalChargeTextField;
    private javax.swing.JTextField TotalPaidTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
