
package hospital_managment_system;
import java.sql.*;
import hospital_managment_system.DatabaseHandler;


public class List extends javax.swing.JDialog {

    
    
    public List(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Patients List");
        

        try (Connection conn = DatabaseHandler.getConnection();) {

            int id = 1001;
            int last = DatabaseHandler.getLastPatientId();
        double charge, paid, money;
        int age, room;
        String name, gender, address, disease, treatment, medicine;
            
            while (id <= last) {
                    
                    name = DatabaseHandler.getPatientNameById(id);
                    age = DatabaseHandler.getPatientAgeById(id);
                    gender = DatabaseHandler.getPatientGenderById(id);
                    address = DatabaseHandler.getPatientAddressById(id);
                    disease = DatabaseHandler.getPatientDiseaseById(id);
                    treatment = DatabaseHandler.getPatientTreatmentById(id);
                    medicine = DatabaseHandler.getPatientMedicineById(id);
                    room = DatabaseHandler.getPatientRoomById(id);
                    charge = DatabaseHandler.getPatientTotalChargeById(id);
                    paid = DatabaseHandler.getPatientTotalDepositedById(id);
                    money = DatabaseHandler.getPatientMoneyToReturnById(id);
                String s = "ID: "+id+"\n"+"Name: "+name+"\n"+"Age: "+age+"\n"+"Gender: "+gender+"\n"+"Address: "+address+"\n"+"Disease: "+disease+"\n"+"Treatment: "+treatment+"\n"+"Medicine: "+medicine+"\n"+"Room: "+room+"\n"+"Total Charge: "+charge+"\n"+"Total Deposited: "+paid+"\n"+"Money To Return: "+money+"\n"+"\n"+"\n"+"\n";
                    ListTextArea.append(s);
                id++;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ListTextArea.setColumns(20);
        ListTextArea.setRows(5);
        ListTextArea.setText("Patients List:");
        jScrollPane1.setViewportView(ListTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ListTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
