
package hospital_managment_system;
import hospital_managment_system.DatabaseHandler;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class SearchNew extends javax.swing.JDialog {

    /**
     * Creates new form Add
     */
    int id;
    double charge, paid, money;
    int age, room;
    String name, gender, address, disease, treatment, medicine;
    public SearchNew(java.awt.Frame parent, boolean modal, int Id) {
        super(parent, modal);
        initComponents();
        setTitle("Search");
        id = Id;
        name = DatabaseHandler.getPatientNameById(id);
        age = DatabaseHandler.getPatientAgeById(id);
        gender = DatabaseHandler.getPatientGenderById(id);
        address = DatabaseHandler.getPatientAddressById(id);
        disease = DatabaseHandler.getPatientDiseaseById(id);
        treatment = DatabaseHandler.getPatientTreatmentById(id);
        medicine = DatabaseHandler.getPatientMedicineById(id);
        room = DatabaseHandler.getPatientRoomById(id);
        charge = DatabaseHandler.getPatientTotalChargeById(id);
        paid = DatabaseHandler.getPatientTotalDepositedById(id);
        money = DatabaseHandler.getPatientMoneyToReturnById(id);
        IDTextField.setText(String.valueOf(id));
        NameTextField.setText(name);
        AgeTextField.setText(String.valueOf(age));
        GenderTextField.setText(gender);
        AddressTextField.setText(address);
        DiseaseTextArea.setText(disease);
        TreatmentTextField.setText(treatment);
        MedicineTextField.setText(medicine);
        RoomTextField.setText(String.valueOf(room));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        GenderTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        TreatmentTextField = new javax.swing.JTextField();
        MedicineTextField = new javax.swing.JTextField();
        RoomTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DiseaseTextArea = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        FinancialButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Age:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Disease Description:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Treatment:");

        DeleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Medicine:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Specialist Room:");

        NameTextField.setText(name);
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        AgeTextField.setText(String.valueOf(age));

        GenderTextField.setText(gender);

        AddressTextField.setText(address);

        TreatmentTextField.setText(treatment);

        MedicineTextField.setText(medicine);

        RoomTextField.setText(String.valueOf(room));

        DiseaseTextArea.setColumns(20);
        DiseaseTextArea.setRows(5);
        DiseaseTextArea.setText(disease);
        jScrollPane1.setViewportView(DiseaseTextArea);

        SaveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        IDTextField.setText(String.valueOf(id));
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        FinancialButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FinancialButton.setText("Financials");
        FinancialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinancialButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DeleteButton)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameTextField)
                    .addComponent(AgeTextField)
                    .addComponent(GenderTextField)
                    .addComponent(AddressTextField)
                    .addComponent(TreatmentTextField)
                    .addComponent(MedicineTextField)
                    .addComponent(RoomTextField)
                    .addComponent(jScrollPane1)
                    .addComponent(IDTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinancialButton)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TreatmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(RoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton)
                    .addComponent(SaveButton)
                    .addComponent(FinancialButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try{
        DatabaseHandler.deletePatientById(id);
        JOptionPane.showMessageDialog(null, "User was deleted successfully");
        this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "User wasn't deleted something went wrong!");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void FinancialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinancialButtonActionPerformed
        // TODO add your handling code here:
        Financials pop; // 'this' refers to your GUI JFrame
        pop = new Financials(this, true, id, charge, paid, money);
            pop.setLocationRelativeTo(this); // centers the dialog on top of the parent
            pop.setVisible(true); // this will make it appear as a popup
    }//GEN-LAST:event_FinancialButtonActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn=DatabaseHandler.getConnection();
            int i;
        i = Integer.parseInt(IDTextField.getText());
        name = NameTextField.getText();
        age = Integer.parseInt(AgeTextField.getText());
        gender = GenderTextField.getText();
        address = AddressTextField.getText();
        disease = DiseaseTextArea.getText();
        treatment = TreatmentTextField.getText();
        medicine = MedicineTextField.getText();
        room = Integer.parseInt(RoomTextField.getText());
        if (conn == null) {
        JOptionPane.showMessageDialog(null, "Connection failed");
        } else {
        System.out.println("Connection successful!");
        }
        
        Statement stmt = conn.createStatement();
        String sql;
        sql ="UPDATE `hospitalmanagmentsystem` SET `ID`='"+i+"',`Name`='"+name+"',`Age`='"+age+"',`Gender`='"+gender+"',`Address`='"+address+"',`Disease`='"+disease+"',`Treatment`='"+treatment+"',`Medicine`='"+medicine+"',`Room`='"+room+"' WHERE ID = "+id+"";
        stmt.executeUpdate(sql);

        IDTextField.setText(String.valueOf(i));
        NameTextField.setText(name);
        AgeTextField.setText(String.valueOf(age));
        GenderTextField.setText(gender);
        AddressTextField.setText(address);
        DiseaseTextArea.setText(disease);
        TreatmentTextField.setText(treatment);
        MedicineTextField.setText(medicine);
        RoomTextField.setText(String.valueOf(room));
        id = i;
            JOptionPane.showMessageDialog(null, "Patient Updated Successfully");
        
        
            
            stmt.close();
            conn.close();
            

            
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error Occured Try Again");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextArea DiseaseTextArea;
    private javax.swing.JButton FinancialButton;
    private javax.swing.JTextField GenderTextField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField MedicineTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField RoomTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField TreatmentTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
